[package]
name = "Gaming-Degree-Tracker"
version = "0.1.2"
description = "Gaming Degree Site"
publish = { registries = ["wasmer"] }

[[command]]
name = "serve"
module = { inherit = true }
runner = "https://webassets.wasmer.sh/runners/http-server/http_server.wasm"

[fs]
"/" = "."
